name: test1907
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
      sdk: flutter
  intl: ^0.19.0
  flutter_native_splash: ^2.4.1
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.18
  audioplayers: ^1.0.1  # تم تحديث الإصدار هنا
lottie: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/files/
